{
    'name': 'Corporate Planning',
    'version': '1.0',
    'author': 'Niyat ERP',
    'summary': 'Planning for Corporate',
    'depends': [
        'base',
        'hr',
        'hr_holidays',
        'uom',
        'hr_kpi_appraisal',
        'mail',
        'project',
        'account',
    ],
    'data': [
        'security/security_groups.xml',
        'security/ir.model.access.csv',
        'security/security_rules.xml',
        'wizard/hr_budget_wizard_view.xml',
        'views/annual_plan_view.xml',
        'views/budget_hr_view.xml',
        'views/budget_training_view.xml',
        'views/budget_project_view.xml',
        'views/budget_general_view.xml',
        'reports/strategy_document_report.xml',
        'views/strategy_document_view.xml',
        'reports/strategy_analysis_report.xml',
        'views/strategy_analysis_view.xml',
        'views/risk_view.xml',
        'views/performance_monitoring_view.xml',
        'views/operating_plan_view.xml',
        'views/project_integration_view.xml',
        'views/performance_report_view.xml',
        'data/quarter_data.xml',
        'views/operational_plan_view.xml',
        'views/reporting_view.xml',
        'reports/annual_plan_report.xml',
        'views/okr_view.xml',
        'views/okr_reporting.xml',
        'views/execution_tracking_view.xml',
        'views/plan_vs_actual_view.xml',
        'views/master_data_view.xml',
        'views/menus.xml',
        'views/dashboard_action.xml',
        
    ],
    'assets': {
        'web.assets_backend': [
            'corporate_planning/static/src/css/dashboard.css',
            'corporate_planning/static/src/xml/dashboard.xml',
            'corporate_planning/static/src/xml/dashboard_pva.xml',
            'corporate_planning/static/src/js/dashboard_pva.js', 
            'corporate_planning/static/src/js/dashboard.js',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}