[options]
addons_path = /usr/lib/python3/dist-packages/odoo/addons,/mnt/addons,/mnt/addons_e,/mnt/project,/mnt/accounting,/mnt/fleet,/mnt/hr,/mnt/inv_purchase_sales,/mnt/manufacturing,/mnt/theme
admin_passwd = odooepr@loyal
; loyalit@2021@erp
csv_internal_sep = ,
data_dir = /var/lib/odoo
db_host = db
db_maxconn = 64
db_name = False
db_password = odoo18@2021
db_port = 5432
db_sslmode = prefer
db_template = template0
db_user = odoo
dbfilter = 
demo = {}
email_from = False
from_filter = False
geoip_database = /usr/share/GeoIP/GeoLite2-City.mmdb
http_enable = True
http_interface = 
http_port = 8069
proxy_mode = True
import_partial = 
; list_db = True
list_db = True
log_db = False
log_db_level = warning
log_handler = :INFO
log_level = info
logfile = /etc/odoo/odoo-server.log
longpolling_port = 8072

xmlrpcs = True
xmlrpc = True
unaccent = False
translate_modules = ['all']
server_wide_modules = base,web,web_editor
workers = 0
max_cron_threads = 1
default_productivity_apps = False

