{
    'name': 'Stock Picking GRN Report',
    'summary': 'GRN, delivery notes, attachments, and related picking PDFs',
    'category': 'Inventory',
    'version': '18.0.1.0.8',
    'depends': [
        'stock',
        'sale_stock',
        'purchase_stock',
        'stock_picking_custom',
        'store_request',
    ],
    'data': [
        'report/paper_format.xml',
        'reports/customer_delivery_note_report.xml',
        'reports/customer_good_receiving_note_report.xml',
        'reports/get_pass_attachment_report.xml',
        'reports/good_receiving_attachment_report.xml',
        'reports/delivery_note_attachment_report.xml',
        # 'views/stock_picking_views.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': 'LGPL-3',
}
