{
    'name': "Company Tender Management",
    'version': '1.0',
    'summary': "Track and manage tender participation and sales performance.",
    'author': "Henok Gm",
    'depends': ['base', 'mail', 'agreement', 'customer_vetting', 'sale', 'custom_sale_agreement'], 
    'data': [
        'security/ir.model.access.csv',
        'data/ir_sequence_data.xml',
        'report/bid_power_attorney_report.xml',
        'report/warranty_form_report.xml',
        'views/tender_lost_wizard_views.xml',
        'views/tender_request_views.xml',
        'views/tender_stage_views.xml',
        'views/agreement_views.xml',
        'views/res_company_views.xml',
        'views/payment_request_views.xml',
        'views/bid_power_attorney_views.xml',
        'views/warranty_form_views.xml',
        'views/bid_bond_views.xml',
    ],
    'installable': True,
    'application': True,
}