{
    'name': 'Invetory Report',
    'version': '18.0.0.1',
    'summary': 'This module help you to generate inventory report',
    'description': """This module help you to generate inventory report""",
    'category': 'Inventory',
    'website': '',
    'depends': [
        'base',
        'mrp',
        'purchase',
        'product',
        'mrp',
        # 'approvals',
        'stock'],
    'license': 'LGPL-3',
    'data': [
        'security/ir.model.access.csv',
        'views/stock_balance_report_view.xml',
        'views/manufacturing_balance_report.xml',
        'views/stock_bin_card_report.xml',
        'reports/inventory_report.xml',
        'wizard/inventory_balance_report.xml',
        'reports/manufacturing_report_view.xml',
        'reports/inventory_print_docs.xml',
        # 'reports/purchase_request_print_doc.xml',
        'reports/bin_card_report.xml',
        # 'reports/store_requstion_voucher.xml',
        # 'reports/store_issue_document.xml',
        # 'reports/production_order_doc.xml',
        'wizard/bin_card_report_wizard.xml',
        'wizard/manufacturing_report_wizard_view.xml',
    ],
    'assets': {},
    'installable': True,
    'application': True,
}
