from . import ir_actions
from . import stock_picking
from . import stock_return_picking
from . import sale_order
from . import account_move
from . import mrp_production
from . import maintenance_equipment
from . import store_request
from . import hr_employee