# -*- coding: utf-8 -*-
{
    'name': 'Custom Sale Agreement',
    'version': '18.0.1.0.0',
    'summary': 'Adds custom fields and auto-sequences to Sale Agreements',
    'category': 'Sales/Sales',
    'author': 'Henok Gm',
    'depends': [
        'agreement',
        'mrp',
        'mail',
        'VendorBid',
    ],
    'data': [
        'security/security_groups.xml',
        'security/ir.model.access.csv',
        'data/product_warranty_sequence.xml',
        'data/purchase_request_sequence.xml',
        'data/sale_agreement_sequence.xml',
        'data/payment_request_sequence.xml',
        'data/ir_sequence.xml',
        'report/payment_request_report.xml',
        'report/sale_agreement_report.xml',
        'report/sale_agreement_template.xml',
        'report/contract_request_report.xml',
        'report/cip_request_report.xml',
        'report/product_warranty_report.xml',
        'report/purchase_request_report.xml',
        'views/payment_request_views.xml',
        'views/purchase_request_views.xml',
        'views/sale_order_extension_views.xml',
        'views/mrp_production_views.xml',
        'views/sale_agreement_document_wizard_views.xml',
        'views/sale_agreement_views.xml',
        'views/sale_order_views.xml',
        'views/request_views.xml',
        'views/cip_request_views.xml',
        'views/contract_request_views.xml',
        'views/product_warranty_views.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}