{
    'name': 'HR Contract Letters',
    'version': '1.0',
    'category': 'Human Resources',
    'summary': 'Print and Email functionality for HR Contracts',
    'description': '''
        This module adds print and email functionality to HR contracts.
        Features:
        - Print contract as PDF
        - Send contract by email with PDF attachment
    ''',
    'depends': ['hr_contract', 'hr', 'mail', 'ent_ohrms_loan', 'hr_contract_salary', 'training_requisition'],
    'data': [
        'security/offer_group_acc.xml',
        'security/ir.model.access.csv',
        'report/hr_contract_report.xml',
        'report/hr_contract_email_template.xml',
        'report/hr_contract_confirmation_report.xml',
        'report/hr_contract_confirmation_email_template.xml',
        'report/hr_contract_job_description_report.xml',
        'report/hr_contract_job_description_email_template.xml',
        'report/hr_contract_extension_report.xml',
        'report/hr_contract_extension_email_template.xml',
        'report/hr_contract_loan_agreement_report.xml',
        'report/hr_contract_loan_agreement_email_template.xml',
        'report/hr_contract_guarantee_report.xml',
        'report/hr_contract_guarantee_email_template.xml',
        'report/hr_contract_acting_report.xml',
        'report/hr_contract_acting_email_template.xml',
        'report/hr_contract_salary_adjustment_report.xml',
        'report/hr_contract_salary_adjustment_email_template.xml',
        'report/hr_contract_delegation_report.xml',
        'report/hr_contract_delegation_email_template.xml',
        'report/hr_contract_experience_report.xml',
        'report/hr_contract_experience_email_template.xml',
        'report/hr_contract_resignation_acceptance_report.xml',
        'report/hr_contract_resignation_acceptance_email_template.xml',
        'report/hr_contract_salary_increment_report.xml',
        'report/hr_contract_salary_increment_email_template.xml',
        'report/hr_contract_temporary_assignment_report.xml',
        'report/hr_contract_temporary_assignment_email_template.xml',
        'report/hr_training_invitation_report.xml',
        'report/hr_training_invitation_email_template.xml',
        'wizard/hr_contract_send_wizard_view.xml',
        'wizard/hr_loan_send_wizard_view.xml',
        'wizard/hr_training_invitation_send_wizard_view.xml',
        'views/hr_training_requisition_view.xml',
        'views/hr_contract_view.xml',
        'views/hr_loan_view.xml',
        'views/hr_loan_fields_view.xml',
        'views/company_view.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': False,
    'post_init_hook': 'models.hr_training_requisition_init.post_init_hook',
}
