# -*- coding: utf-8 -*-
from . import res_company
from . import res_config_settings
from . import res_partner
from . import sales_territory
from . import sales_plan
from . import sales_target_line
from . import share_mixin
from . import share_history
from . import cheque_register
from . import account_payment
from . import sale_order
from . import sale_order_line
from . import account_move
from . import account_move_line
from . import stock_rule
from . import stock_move
from . import stock_picking
from . import stock_lot
from . import purchase_order
