# custom_stock_reports/__manifest__.py
{
    'name': 'Stock Picking Custom',
    'summary': 'Customizes the Delivery Slips and Receipts to match company format.',
    'category': 'Inventory',
    'depends': [
        'stock',
        'store_request',
        'purchase_stock',
        'sale_stock',
        'sale',
        'account',
        'sale_pdf_quote_builder',
        'mrp',
        'custom_report_layout',
    ],
    'data': [
        'data/stock_report_actions.xml',
        'data/sale_report_actions.xml',
        'data/mrp_report_actions.xml',
        'reports/picking_operations_template.xml',
        'reports/sales_proforma_invoice_report.xml',
        'reports/sales_order_attachment_report.xml',
        'reports/report_invoice.xml',
        'reports/manufacturing_order_attachment_report.xml',
        'reports/store_return_attachment_report.xml',
        # 'reports/report_deliveryslip.xml',
        'views/sale_order_views.xml',
        'views/account_move_views.xml',
        'views/stock_picking_view.xml',
        'views/stock_return_picking_views.xml',
        'views/maintenance_equipment_view.xml',
        'views/store_request_view.xml',
        'views/hr_employee_view.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
}
